# Generated by Django 3.1.7 on 2021-04-14 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listapp', '0002_auto_20210402_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_add_user', 'Может внести работника')]},
        ),
    ]
