# Generated by Django 3.1.7 on 2021-04-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='git_profile',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
