# Generated by Django 3.1.7 on 2021-04-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_git_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='git_profile',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
