# Generated by Django 3.1.7 on 2021-04-19 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210416_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_view_userlist', 'может видеть список пользователей')], 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
